# Generated by Django 3.1 on 2020-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('main_content', models.TextField()),
                ('sub_content', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
