# Generated by Django 3.1 on 2020-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('general_description', models.CharField(max_length=300)),
                ('solo_exhibitions', models.TextField(blank=True)),
                ('group_exhibitions', models.TextField(blank=True)),
                ('awards_residencies', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
                ('current_employment', models.TextField(blank=True)),
                ('public_collection', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
