# Generated by Django 3.1 on 2020-08-26 07:13

import artsite.apps.gallery.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(unique=True)),
                ('description', models.CharField(max_length=300)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('download', models.FileField(upload_to=artsite.apps.gallery.models.file_upload_path)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=1)),
                ('order', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(unique=True)),
                ('date_created', models.DateField()),
                ('medium', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=artsite.apps.gallery.models.work_image_path)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_primary_image', models.BooleanField()),
                ('quote', models.TextField(blank=True)),
                ('quote_byline', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
